prometheus-exporter:
    image: neuvector/prometheus-exporter
    container_name: neuvector.prometheus-exporter
    environment:
        - CTRL_API_SERVICE=neuvector-svc-prometheus-exporter.neuvector:10443
        - CTRL_USERNAME=admin
        - CTRL_PASSWORD=admin
        - EXPORTER_PORT=8068
    ports:
        - 8068:8068
